apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-dynamic-example
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-dynamic-retain
